/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-j270sdr
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_J270SDR_API_H
#define INCLUDED_J270SDR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_j270sdr_EXPORTS
#define J270SDR_API __GR_ATTR_EXPORT
#else
#define J270SDR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_J270SDR_API_H */
