/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(J270SDRReceiver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d1f915358da2267f8b78120096a8ee67)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <j270sdr/J270SDRReceiver.h>
// pydoc.h is automatically generated in the build directory
#include <J270SDRReceiver_pydoc.h>

void bind_J270SDRReceiver(py::module& m)
{

    using J270SDRReceiver    = gr::j270sdr::J270SDRReceiver;


    py::class_<J270SDRReceiver, gr::block, gr::basic_block,
        std::shared_ptr<J270SDRReceiver>>(m, "J270SDRReceiver", D(J270SDRReceiver))

        .def(py::init(&J270SDRReceiver::make),
           py::arg("points"),
           py::arg("dds"),
           D(J270SDRReceiver,make)
        )
        



        ;




}








