/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(J270SDRTransmitter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4aa7437197f49fd72c43d65ef48f62ae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/j270sdr/J270SDRTransmitter.h>
// pydoc.h is automatically generated in the build directory
#include <J270SDRTransmitter_pydoc.h>

void bind_J270SDRTransmitter(py::module& m)
{

    using J270SDRTransmitter    = gr::j270sdr::J270SDRTransmitter;


    py::class_<J270SDRTransmitter, gr::block, gr::basic_block,
        std::shared_ptr<J270SDRTransmitter>>(m, "J270SDRTransmitter", D(J270SDRTransmitter))

        .def(py::init(&J270SDRTransmitter::make),
           D(J270SDRTransmitter,make)
        )
        



        ;




}








