/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(VirtualModulation.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8d9f8c90aa66bfcb7dc2b2b410b3c24e)                     */
/***********************************************************************************/

#include "docstrings/VirtualModulation_pydoc_template.h"


#include <J270SDRTransmitter_pydoc.h>
#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/j270sdr/VirtualModulation.h>
// pydoc.h is automatically generated in the build directory

void bind_VirtualModulation(py::module& m)
{

    using VirtualModulation    = gr::j270sdr::VirtualModulation;


    py::class_<VirtualModulation, gr::block, gr::basic_block,
        std::shared_ptr<VirtualModulation>>(m, "VirtualModulation", D(VirtualModulation))

        .def(py::init(&VirtualModulation::make),
           D(VirtualModulation,make)
        )
        



        ;




}








