/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(VirtualBasicLayer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7f57e586eb6305c0cb249b1e48cda961)                     */
/***********************************************************************************/

#include "docstrings/VirtualBasicLayer_pydoc_template.h"


#include <J270SDRTransmitter_pydoc.h>
#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/j270sdr/VirtualBasicLayer.h>
// pydoc.h is automatically generated in the build directory

void bind_VirtualBasicLayer(py::module& m)
{

    using VirtualBasicLayer    = gr::j270sdr::VirtualBasicLayer;


    py::class_<VirtualBasicLayer, gr::block, gr::basic_block,
        std::shared_ptr<VirtualBasicLayer>>(m, "VirtualBasicLayer", D(VirtualBasicLayer))

        .def(py::init(&VirtualBasicLayer::make),
           D(VirtualBasicLayer,make)
        )
        



        ;




}








